import Mock from 'mockjs';
import mockApiUrl from '../mock-config';

Mock.mock(`${mockApiUrl.vueList}`, 'post', {
  'data': [
    {
      title: '你知道vue的模板语法用的是哪个web模板引擎的吗？说说你对这模板引擎的理解',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点1',
      content: 'VueJS作为一个前端框架，少不了模板引擎的功能，为了优化模板引擎，Vue会在编译阶段把template转化为render函数，在编译阶段之前（预编译阶段）我们可以定制一些模板引擎的行为，比如文本插入分隔符、指令、过滤器',
      linkPage: 'https://blog.csdn.net/qq_41047322/article/details/82935877',
    },
    {
      title: '你知道v-model的原理吗？说说看',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点2',
      content: 'v-model只是一个语法糖，等于:value+@input，真正的实现靠的还是： ﻿v-bind:绑定响应式数据，触发 input 事件并传递数据 (核心和重点)',
      linkPage: 'https://www.kancloud.cn/dataoedu/vue/327250',
    },
    {
      title: '你有使用过vue开发多语言项目吗？说说你的做法？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点3',
      content: '多语言，走国际化，那么就需要切换语言和识别地区；一款vue-i18n插件，做这方便比较方便',
      linkPage: 'https://github.com/kazupon/vue-i18n',
    },
    {
      title: '在使用计算属性的时，函数名和data数据源中的数据可以同名吗？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点4',
      content: '不能同名 因为不管是计算属性还是data还是props 都会被挂载在vm实例上，因此 这三个都不能同名',
      linkPage: 'https://www.jianshu.com/p/ae99e8b96c06',
    },
    {
      title: 'vue中data的属性可以和methods中的方法同名吗？为什么？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点5',
      content: '他们都作为属性加到this中去了，所以要注意data中的命名不能和methods中冲突',
      linkPage: 'https://github.com/haizlin/fe-interview/issues/557',
    },
    {
      title: '怎么给vue定义全局的方法？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点6',
      content: '第一种：挂载到Vue的prototype上。把全局方法写到一个文件里面，然后for循环挂载到Vue的prototype上，缺点是调用这个方法的时候没有提示；第二种：利用全局混入mixin，因为mixin里面的methods会和创建的每个单文件组件合并。这样做的优点是调用这个方法的时候有提示',
      linkPage: 'https://www.jianshu.com/p/7547ff8760c3',
    },
    {
      title: 'vue2.0不再支持v-html中使用过滤器了怎么办？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点7',
      content: '在method中定义方法',
      linkPage: 'https://github.com/haizlin/fe-interview/issues/555',
    },
    {
      title: '怎么解决vue打包后静态资源图片失效的问题？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点8',
      content: "设置assetsPublicPath将 assetsPublicPath: ' / ' 改为 assetsPublicPath: './ '",
      linkPage: 'https://blog.csdn.net/jian_xi/article/details/70158952',
    },
    {
      title: '怎么解决vue动态设置img的src不生效的问题？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点9',
      content: "原因是vue并没有把你的路径字符串当做路径来处理，而是直接当做字符串了,可以在开始的时候进行import引入，或者在data里面进行require引入",
      linkPage: 'https://segmentfault.com/q/1010000004582219',
    },
    {
      title: '使用vue后怎么针对搜索引擎做SEO优化？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点10',
      content: '使用服务端渲染，vue官方推荐nuxt.js',
      linkPage: 'https://blog.csdn.net/jian_xi/article/details/70158952',
    },
    {
      title: '跟keep-alive有关的生命周期是哪些？描述下这些生命周期',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点11',
      content: '在被keep-alive包含的组件/路由中，会多出两个生命周期的钩子:activated 与 deactivated',
      linkPage: 'https://juejin.im/entry/5b7585e4518825332755c4da',
    },
    {
      title: '如果现在让你从vue/react/angularjs三个中选择一个，你会选哪个？说说你的理由',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点12',
      content: '团队技术积累 哪个熟练有积累 哪个优先',
      linkPage: 'https://blog.csdn.net/qq_26780317/article/details/88656036',
    },
    {
      title: '你知道vue2.0兼容IE哪个版本以上吗？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点13',
      content: '不支持ie8及以下，部分兼容ie9 ，完全兼容10以上',
      linkPage: 'https://my.oschina.net/u/171860/blog/1831843',
    },
    {
      title: '你有看过vue推荐的风格指南吗？列举出你知道的几条',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点14',
      content: '1、组件名称见名知意，最好加特殊前缀，如：el-Button、el-row等；2、组件的prop尽可能描述的越详细越好；3、为组件样式设置scoped作用域',
      linkPage: 'https://cn.vuejs.org/v2/style-guide/index.html',
    },
    {
      title: '你知道vue中key的原理吗？说说你对它的理解',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点15',
      content: '作用的话，便于diff算法的更新，key的唯一性，能让算法更快的找到需要更新的dom，需要注意的是，key要唯一，不然会出现很隐蔽性的更新问题',
      linkPage: 'https://www.jianshu.com/p/32943c14ee66',
    },
    {
      title: 'vue中怎么重置data？',
      time: Mock.Random.time('A HH:mm:ss'),
      id: '知识点16',
      content: '使用Object.assign()，vm.$data可以获取当前状态下的data，vm.$options.data可以获取到组件初始化状态下的data，具体可以看vm.$options。',
      linkPage: 'https://cn.vuejs.org/v2/api/#vm-options',
    },
  ],
});